### ISSUE TITLE
(bug) Player Data returns String on ESX

### ISSUE THREAD

**Issue by Mobilcek** [DonHulieo/duf#1]
in console F8 gives me this error after upgrade
![image](https://github.com/DonHulieo/duff/assets/109557778/eba2a0da-b3f6-4519-b502-e63da72d4583)

**Comment by DonHulieo** [comment]
Hey mate, which framework are you using?

**Comment by Mobilcek** [comment]
esx

**Comment by DonHulieo** [comment]
@Mobilcek latest updates should rectify the issue, will push a release if that's the case.

**Comment by Mobilcek** [comment]
![image](https://github.com/DonHulieo/duff/assets/109557778/a204df65-58bd-4ea3-8fe6-582000dc9ceb)

**Comment by DonHulieo** [comment]
@Mobilcek I'd ensure `duff` is starting before `don-trafficlights`, unless there's an error in `duff` starting. The require export being nil is not possible.

**Comment by Mobilcek** [comment]
![image](https://github.com/DonHulieo/duff/assets/109557778/50f6a214-126c-4854-8ca4-e59db61fd646)
![image](https://github.com/DonHulieo/duff/assets/109557778/838032d0-27dd-4ca0-93de-20bd6dcdc7fd)
duff is run first

**Comment by DonHulieo** [comment]
I have the feeling you've just downloaded release again instead of the most updated version, however the new release has the fixes for the above issue included, see [v1.0.2](https://github.com/DonHulieo/duff/releases/tag/v1.0.2).
